### ISSUE TITLE
Can it replace Gulp?

### ISSUE THREAD

**Issue by jamm** [omeid/slurp#1]
Can I replace Gulp by this tool, minify and concatenate JS files?

**Comment by omeid** [comment]
Yes. I will push a proper example in a little while.

**Comment by omeid** [comment]
Please see the obligatory [Todo App](https://github.com/omeid/slurp-todo) as a reference until I get the time to write documentation.

**Comment by jamm** [comment]
SPA with server-side rendering is funny. But hardcoded paths in .go file is not even funny, sorry.

**Comment by omeid** [comment]
@jamm Slurp has no opinion about how you handle your templates or anything about your frontend, it just provides the tools to connect the dots.

First of all, there is no server-side rendering here, it is just precompiling Ace templates to html, this will happen once, you will bundle your app with the "public" directory and the binary that you get which doesn't include the build tools, including the ace compiler.

It is a very common pattern to write your Angular.js templates in a language that is lighter than html that compiles to it and then use angular-template cache and then use them in your frontend.

I am not sure about your point about paths in .go files.

**Comment by jamm** [comment]
Hardcoded paths to libs:
https://github.com/omeid/slurp-todo/blob/master/slurp.go#L30
https://github.com/omeid/slurp-todo/blob/master/slurp.go#L42

And paths to "public" and "libs" better to move into variables or configuration file. Go is compiling language so I thought Slurp will be used as binary file - it could be killer-feature, when you don't need to install Node/io.js environment to prepare static assets. But if you need Go environment.. Will be only attractive for Go projects.

**Comment by omeid** [comment]
The url paths are hardcoded in the very much the same way you hard package names and versions in your package managers, there is no way to go around it.

And the "public" and "libs" paths, although not entirely arbitrary, are my personal choice for that given project, Slurp doesn't impose any opinion about how you should write your builds beyond the task definitions, the "libs" task could very well be programmed to read the list of urls from a json or any other configuration file before passing it to the `web.Get`, that is the point of Slurp: Choice.

And on being able to compile, I just introduced the `-build` flag, if you run `slurp -build` from the todo project directory, you will be provided with a `slurp-bin` that will have all the tasks defined in `slurp.go` and you can run it without `slurp` or `go`, it will just another program.

I have also updated the about me, let me know if it is still not clear.

**Comment by jamm** [comment]
Actually all builders I know takes paths from index.html and have no hardcoded paths. And as side effect of it, both versions, built and raw, are runnable.

**Comment by omeid** [comment]
The paths (urls) are not part of the web app, they're external packages that downloaded, the "libs" task is doing what you basically do with `bower` or `npm`. 

The "libs" paths again is what it would normally be `bower_components` or `node_modules`. 

The end product of that todo app is the binary that you get from `go build` and whatever ends up in `public` after you run `slurp frontend` none of which has any refernce to the urls in slurp.go or "libs" path.

**Comment by jamm** [comment]
You are missing the point. Edit generator file (slurp.go) each time to add new lib means you can't make this file binary. Also, deploying binary file (if it's the result of Slurp work) is not always the case - see how Google App Engine works. To see how other builders work, I recommend to try this: https://github.com/Swiip/generator-gulp-angular

Sorry, this task takes too much of my time, I'm unsubscribing.

**Comment by omeid** [comment]
Slurp isn't a generator.
