### ISSUE TITLE
web.Get resource issue

### ISSUE THREAD

**Issue by LukeMauldin** [omeid/slurp#14]
file.go defines File to contain an `io.Reader` but is assigned a Response.Body, which implements `io.ReadCloser` in http.go:38.  According to the standard library, it is the caller's responsibility to close the body: http://golang.org/src/net/http/response.go?s=512:2670#L19

file.go should be changed to contain an `io.ReadCloser` and callers should be changed to Close it upon completion.

**Comment by omeid** [comment]
The file contains an `io.Reader` for convince however as it is an interface, the [closing is managed through a type assertion](https://github.com/omeid/slurp/blob/554dd8ea253f9bbe9b535aa6fec624773b8e4e70/file.go#L32-L41) whenever the file.Reader is actually an io.Closer.

I hope this answers your concern.

**Comment by LukeMauldin** [comment]
This addresses my concern, although a comment in the struct might be nice for clarity.
