### ISSUE TITLE
Slurp fails with multiple GOPATH directories

### ISSUE THREAD

**Issue by GeertJohan** [omeid/slurp#8]
Thanks for this awesome project!

I use a double gopath. The go tool allows to set multiple paths, separated by a colon. Both paths are searched for packages, new packages downloaded with go-get are downloaded to the first gopath. This way the second gopath stays very clean and only contains code you put there yourself.

https://golang.org/cmd/go/#hdr-GOPATH_environment_variable

I think slurp should recognize this and select the GOPATH in which the slurp.go tasks file is located.

Get the following error on `slurp init`:
"go install: no install location for directory /home/geertjohan/Workspaces/Go/gopath:/devpath/src/github.com/OpenRA-Zone/tesla/tmp outside GOPATH`"

**Comment by GeertJohan** [comment]
I've started working on a fix

**Comment by omeid** [comment]
I don't use multiple paths which is why I totally forgot about it.

But if the official go tools supports such a setup, so should slurp.
